import { ScaledSheet } from 'react-native-size-matters';

import { COLORS } from '../../constants/colors';

export const styles = ScaledSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  titleContainer: {
    marginTop: '10@vs',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '10@s',
    paddingHorizontal: '10@s',
  },
  titleLeft: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  title: {
    fontFamily: 'Montserrat-Bold',
    fontSize: '17@s',
    color: COLORS.cardinal,
  },
  contentContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.background,
  },
  imageContainer: {
    height: '155@vs',
    width: '155@s',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.white,
    borderRadius: 100,
    overflow: 'hidden',
  },
  image: {
    height: '100%', //'90@s',
    width: '100%', //'90@s',
    resizeMode: 'cover', //'contain',
  },
  cameraIcon: {
    position: 'absolute',
    right: '5@s',
    bottom: '-10@s',
    color: COLORS.cardinal,
    backgroundColor: COLORS.white,
    textAlign: 'center',
    padding: '7@s',
    borderRadius: 50,
    height: '40@vs',
    width: '40@s',
  },
  containerGlass: {
    marginTop: '20@vs',
    backgroundColor: 'white',
    borderRadius: '7@s',
    width: '90%',
    padding: '15@s',
  },
  accountContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginTop: '15@vs',
  },
  inputsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: '15@vs',
    gap: 10,
    backgroundColor: COLORS.background,
    paddingHorizontal: '10@s',
    paddingVertical: '6@vs',
    borderRadius: 5,
  },
  textInput: {
    backgroundColor: COLORS.background,
    paddingHorizontal: '10@s',
    paddingVertical: '6@vs',
    flex: 1,
    fontFamily: 'Montserrat-Regular',
    fontSize: '14@s',
  },
  button: {
    backgroundColor: COLORS.cardinal,
    color: COLORS.textBlack,
    paddingVertical: '10@vs',
    paddingHorizontal: '15@s',
    borderRadius: 10,
    minWidth: '180@s',
    alignItems: 'center',
  },
  textButton: {
    fontFamily: 'Montserrat-Bold',
    fontSize: '15@s',
    color: COLORS.white,
  },
  accountTitle: {
    fontFamily: 'Montserrat-Bold',
    fontSize: '13@s',
  },
  accountSubTitle: {
    fontFamily: 'Montserrat-Bold',
    fontSize: '15@s',
    color: COLORS.cardinal,
  },
  accountSubTitleGray: {
    fontFamily: 'Montserrat-Bold',
    fontSize: '15@s',
    color: COLORS.textGray,
  },
});
