export const authTypes = {
  LOADING: 'LOADING',
  SIGNUP: 'SIGNUP',
  SIGNUP_FAILURE: 'SIGNUP_FAILURE',
  SIGNIN: 'SIGNIN',
  SIGNIN_FAILURE: 'SIGNIN_FAILURE',
  SIGNOUT: 'SIGNOUT',
  CLEAN_ERROR: 'CLEAN_ERROR',
};
