export const cartTypes = {
  LOADING: 'LOADING',
  SET_CART: 'SET_CART',
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  CLEAR_CART: 'CLEAR_CART',
  UPDATE_ITEM: 'UPDATE_ITEM',
  DECREMENT_ITEM: 'DECREMENT_ITEM',
};
